# Generated by Django 3.1.5 on 2021-01-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.basemodel')),
                ('book_num', models.CharField(max_length=128, verbose_name='书号')),
                ('book_name', models.CharField(max_length=128, verbose_name='书名')),
                ('book_isbn', models.CharField(max_length=128, null=True, verbose_name='ISBN')),
                ('public_name', models.CharField(max_length=256, verbose_name='出版社名称')),
                ('publish_year', models.CharField(max_length=16, null=True, verbose_name='出版年份')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('translator', models.CharField(max_length=128, null=True, verbose_name='译者')),
                ('edition_order', models.CharField(max_length=32, null=True, verbose_name='版次')),
                ('page_count', models.SmallIntegerField(null=True, verbose_name='总页数')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('remark', models.CharField(max_length=512, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '共享图书',
                'verbose_name_plural': '共享图书',
            },
            bases=('market.basemodel',),
        ),
    ]
