# Generated by Django 3.1.5 on 2021-01-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book_num', models.CharField(default='b944fe4c16e2404db7391a93330a4745', max_length=128, verbose_name='书号')),
                ('book_name', models.CharField(max_length=128, verbose_name='书名')),
                ('book_isbn', models.CharField(max_length=128, null=True, verbose_name='ISBN')),
                ('public_name', models.CharField(max_length=256, verbose_name='出版社名称')),
                ('publish_year', models.CharField(max_length=16, null=True, verbose_name='出版年份')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('translator', models.CharField(max_length=128, null=True, verbose_name='译者')),
                ('edition_order', models.CharField(max_length=32, null=True, verbose_name='版次')),
                ('page_count', models.SmallIntegerField(null=True, verbose_name='总页数')),
                ('status', models.SmallIntegerField(choices=[(0, '待出借'), (1, '出借中')], verbose_name='状态')),
                ('remark', models.CharField(max_length=512, null=True, verbose_name='备注')),
                ('create_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='共享人')),
            ],
            options={
                'verbose_name': '共享图书',
                'verbose_name_plural': '共享图书',
                'db_table': 'market_book',
            },
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
            ],
            options={
                'verbose_name': '我的共享',
                'verbose_name_plural': '我的共享',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.book',),
        ),
    ]
