# Generated by Django 3.1.5 on 2021-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(max_length=128, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.CharField(default='5c52acbbef0c40ffa39bdbb757cd00c8', max_length=128, verbose_name='书号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_order',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版次'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='总页数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='public_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='出版年份'),
        ),
        migrations.AlterField(
            model_name='book',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='译者'),
        ),
    ]
