# Generated by Django 3.1.5 on 2021-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210113_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.CharField(default='de2b6e8164324b96b554af54a7bb712d', max_length=128, verbose_name='书号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='remark',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
    ]
