# Generated by Django 3.1.5 on 2021-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210113_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.CharField(default='38fe3b87a48f47b197999cf543a43897', max_length=128, verbose_name='书号'),
        ),
    ]
