# Generated by Django 3.1.5 on 2021-02-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210223_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.CharField(default='a4205cef977d4814a511e2d0ce311745', max_length=128, verbose_name='书号'),
        ),
    ]
