# Generated by Django 3.1.5 on 2021-02-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210223_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_num',
            field=models.CharField(default='4897b058d4804e94be42336a8c5f33a7', max_length=128, verbose_name='书号'),
        ),
    ]
