# Generated by Django 3.1.5 on 2021-02-23 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_auto_20210223_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qq', models.CharField(blank=True, max_length=32, null=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('return_date', models.DateField(verbose_name='预计还书时间')),
                ('real_return_date', models.DateField(verbose_name='实际还书时间')),
                ('status', models.SmallIntegerField(choices=[(0, '申请借书'), (1, '拒绝申请'), (2, '等待归还'), (3, '已经归还')], default=0, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.book', verbose_name='书籍')),
                ('borrow_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_user', to=settings.AUTH_USER_MODEL, verbose_name='借书人')),
                ('create_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('lend_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lend_user', to=settings.AUTH_USER_MODEL, verbose_name='出借人')),
            ],
            options={
                'verbose_name': '借书记录',
                'verbose_name_plural': '借书记录',
                'db_table': 'borrow_book',
            },
        ),
        migrations.CreateModel(
            name='LendComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('star', models.SmallIntegerField(verbose_name='分数')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowbook', verbose_name='借书记录')),
                ('create_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '出借评价',
                'verbose_name_plural': '出借评价',
                'db_table': 'lend_comment',
            },
        ),
        migrations.CreateModel(
            name='BorrowComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('star', models.SmallIntegerField(verbose_name='分数')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowbook', verbose_name='借书记录')),
                ('create_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '借书评价',
                'verbose_name_plural': '借书评价',
                'db_table': 'borrow_comment',
            },
        ),
    ]
