# Generated by Django 3.1.5 on 2021-02-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='real_return_date',
            field=models.DateField(null=True, verbose_name='实际还书时间'),
        ),
    ]
