# Generated by Django 3.1.5 on 2021-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20210223_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendBook',
            fields=[
            ],
            options={
                'verbose_name': '借书',
                'verbose_name_plural': '借书',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('borrow.borrowbook',),
        ),
        migrations.AlterModelOptions(
            name='borrowbook',
            options={'verbose_name': '出借', 'verbose_name_plural': '出借'},
        ),
        migrations.AlterModelOptions(
            name='borrowcomment',
            options={'verbose_name': '出借评价', 'verbose_name_plural': '出借评价'},
        ),
        migrations.AlterModelOptions(
            name='lendcomment',
            options={'verbose_name': '借书评价', 'verbose_name_plural': '借书评价'},
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请借书'), (1, '拒绝申请'), (2, '等待确认借书'), (3, '等待归还'), (4, '等待确认归还'), (5, '已经归还')], default=0, verbose_name='状态'),
        ),
    ]
